services:
  - type: web
    name: tasksystem-backend
    runtime: php
    repo: https://github.com/Mica2000/Cytonn-Task-Management-System
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://tasksystem.onrender.com
